# Generated by Django 5.2.6 on 2025-09-21 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField()),
                ('age_first_menstrual', models.IntegerField()),
                ('age_first_childbirth', models.IntegerField(blank=True, null=True)),
                ('history_breast_cancer_or_radiation', models.CharField(max_length=10)),
                ('brca_mutation_or_genetic_syndrome', models.CharField(max_length=10)),
                ('biopsy_benign', models.CharField(max_length=10)),
                ('biopsy_benign_count', models.IntegerField(default=0)),
                ('biopsy_atypical_hyperplasia', models.CharField(max_length=10)),
                ('relatives_breast_cancer', models.CharField(max_length=10)),
                ('sub_ethnicity_or_birthplace', models.CharField(blank=True, max_length=100)),
                ('prediction', models.IntegerField()),
                ('probability', models.FloatField()),
                ('confidence_percent', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_name', models.CharField(max_length=255)),
                ('image_size', models.IntegerField(blank=True, null=True)),
                ('prediction', models.IntegerField()),
                ('prediction_label', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('confidence_percent', models.FloatField()),
                ('stage', models.CharField(max_length=50)),
                ('benign_probability', models.FloatField()),
                ('malignant_probability', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
